# The name of our workflow
name: Build
# Trigger on every pull request
on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build