# The name of our workflow
name: Run Lint & Test
# Trigger on every pull request
on:
  pull_request:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run lint check
        run: ./gradlew lintDebug
      - name: Run test
        run: ./gradlew test